image: alpine/edge
packages:
  - nodejs
  - npm
  - go
sources:
  - https://git.sr.ht/~avalos/linkbucket-go
environment:
  LINKBUCKET_PAGINATE_LIMIT: 15
tasks:
  - setup: |
      cd linkbucket-go/client
      npm i
  - build-server: |
      cd linkbucket-go/server
      go mod download
      CGO_ENABLED=0 GOOS=linux go build -a -installsufix cgo -o linkbucket .
  - build-client: |
      cd linkbucket-go/client
      npm install --silent
      npm install react-scripts@3.4.1 -g --silent
      npm run build
